version: "3"
services:
  arxiv-checker:
    container_name: app
    build: ./app
    tty: true
    volumes:
      - ./app:/app
    command: >
      bash -c "cd /app && 
      echo -e '[TOKEN]\ntoken=NzkxOTE5MjA3NzM3NzIwODYy.X-WKPA.nu8iXoY0gf11q0kr-FgG5PIKFWs' > config.ini &&
      python main.py"
    # command: >
    #   bash - c "cd /app && 
    #   python main.py"